services: 
  database:
    container_name: momopoly-pgdatabase
    image: postgres:16.4-alpine
    restart: always
    command: postgres
    ports: 
      - "7838:7832"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes: 
      - postgres_data:/vol/lib/postgresql/data
    networks: 
      - backend

  redis: 
    container_name: monopoly-redis
    image: redis:7.0
    restart: always
    ports: 
     - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} 
    volumes: 
      - redis_data:/data
    networks:
      - backend

volumes: 
  postgres_data:
  redis_data:

networks: 
  backend: