services: 
  database: 
    container_name: momopoly-pgdatabase
    restart: always
    image: postgres:16.4-alpine
    command: postgres
    ports: 
      - "4448:5432"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER_NAME}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes: 
      - postgres_data:/vol/lib/postgresql/data
    networks: 
      - backend


  redis: 
    container_name: monopoly-redis
    image: redis:7.0
    restart: always
    ports: 
     - "4473:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} 
    volumes: 
      - redis_data:/data
    networks:
      - backend

volumes: 
  postgres_data:
  redis_data:

networks: 
  backend: